# Generated by Django 5.0.6 on 2024-08-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_is_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-created_at',)},
        ),
    ]
